<script>
$(document).ready(function(){
  $('.page-alert').fadeIn(1000);
}),
  $(document).ready(function(){
  window.setTimeout(function(){
    $(".alert").fadeTo(700,0).slideUp(500,function(){
      $(this).remove()
    })},2e3)
});
</script>  